name: "auto compile"
on:
  push:
    branches:
      - master
jobs:
  cancel:
    name: Cancel Previous Runs
    runs-on: ubuntu-latest
    steps:
      - name: cancel running workflows
        timeout-minutes: 5
        uses: GongT/cancel-previous-workflows@6dd7af8389c9434cc893fd33b58609e73db49fbe
        env:
          DELETE: "yes"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build:
    name: "构建并上传"
    runs-on: ubuntu-latest
    steps:
      - name: "获取代码"
        uses: actions/checkout@v2
        timeout-minutes: 1
        with:
          submodules: "recursive"
          clean: true
          fetch-depth: 2

      - name: "安装podman"
        shell: bash
        timeout-minutes: 2
        run: sudo apt install podman

      - name: "设置缓存位置"
        shell: bash
        timeout-minutes: 2
        run: bash set-env.sh

      - name: "缓存下载和软件包数据"
        uses: actions/cache@v2
        with:
          path: ${{ env.SYSTEM_COMMON_CACHE }}
          key: common-cache-${{ env.GITHUB_RUN_NUMBER }}
          restore-keys: |
            common-cache-

      - name: "运行构建过程"
        shell: bash
        timeout-minutes: 3
        run: bash build-in-container.sh

      - name: "发布结果"
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: "latest"
          prerelease: false
          title: "Latest Build"
          files: |
            clash/bin/clash-linux-amd64.gz
